# Site settings
author: Nina Angelo
title: Why I decided to learn Software Engineering
header-img: img/home-bg.png
email: ninacelie@gmail.com
copyright_name: Nina Angelo
description: > # this means to ignore newlines until "baseurl:"
  the reasons why
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Ninacelie

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
